micronaut:
  application:
    name: complete
---
#tag::security[]
micronaut:
  security:
    enabled: true # <1>
    endpoints:
      login:
        enabled: true # <2>
      logout:
        enabled: true # <3>
    token:
      jwt:
        enabled: true # <4>
        bearer:
          enabled: false # <5>
        cookie:
          enabled: true # <6>
          loginFailureTargetUrl: /login/authFailed # <7>
        signatures:
          secret:
            generator: # <8>
              secret: pleaseChangeThisSecretForANewOne # <9>
#end::security[]